name: xam_huong
description: Xăm Hường - trò chơi dân gian gieo 6 xí ngầu
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#52BCFD"
  adaptive_icon_foreground: "assets/icon/icon_fg.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#52BCFD"
    theme_color: "#52BCFD"
